spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mowenfeng415
    url: jdbc:mysql://cdb-0uay4vms.bj.tencentcdb.com:10141/ims-cz?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 打印sql
#logging:
#  level:
#    cn.tycoding.biz.mapper: DEBUG
